blogproject/blog/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/2/17 下午4:33
# @Author  : LiuShiYi
# @Site    : 
# @File    : urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'
urlpatterns = [
                  url(r'^$', views.HomePageView.as_view(), name='homepage'),  # 首页
                  url(r'homepage/', views.homepage),
                  url(r'^blog/', views.BlogView.as_view(), name='blog'),  # 博客视图
                  url(r'^img/', views.img, name='img'),  # 图库视图
                  # url(r'^img/', views.ImgView.as_view(), name='img'),
                  url(r'^timeline', views.timeline, name='timeline'),  # 时间轴
                  url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='article'),  # 文章详情
                  url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
                  url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
                  url(r'^search/$', views.search, name='search'),
                  url(r'^test/', views.test),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproject/blogproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls'))
]

blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


# Create your models here.

class Category(models.Model):
    """
    文章分类
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'pk': self.pk})


class Tag(models.Model):
    """
    文章标签
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章详情
    """
    title = models.CharField(max_length=70)  # 标题
    body = models.TextField()  # 正文
    created_time = models.DateTimeField()  # 文章创建时间
    modified_time = models.DateTimeField()  # 文章修改时间
    excerpt = models.CharField(max_length=200, blank=True)  # 文章摘要
    category = models.ForeignKey(Category)  # 文章分类(一篇文章只有一个分类)
    tags = models.ManyToManyField(Tag, blank=True)  # 一篇文章可以有多个标签
    author = models.ForeignKey(User)  # 文章作者
    img = models.ImageField(upload_to='img')

    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)


class ChikenSoup(models.Model):
    """
    心灵鸡汤
    """
    content = models.TextField()  # 鸡汤内容
    img = models.ImageField(upload_to='img')
    reference = models.CharField(max_length=100)  # 出处
    created_time = models.DateField()  # 构建时间

    def __str__(self):
        return self.content


class Img(models.Model):
    """
    图片
    """
    name = models.CharField(max_length=100)  # 图片名称
    img = models.ImageField(upload_to='img')  # 图片
    author = models.CharField(max_length=20) # 图片作者
    params = models.TextField(blank=True) # 参数
    description = models.TextField(blank=True)  # 描述
    upload_time = models.DateTimeField(blank=True)  # 上传时间

    def __str__(self):
        return self.name

blogproject/blog/views.py
import markdown
from markdown.extensions.toc import TocExtension
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from comments.forms import CommentForm
from .models import Post, Category, Tag, ChikenSoup, Img


# Create your views here.

class HomePageView(ListView):
    """
    首页视图
    """
    model = Post
    template_name = 'blog/homepage.html'
    context_object_name = 'post_list'
    paginate_by = 2

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        chicken_soup_data = self.chicken_soup_data()
        tag_data = self.tag_data()
        context.update(chicken_soup_data)
        context.update(tag_data)
        return context

    def chicken_soup_data(self):
        return {
            'chicken_soup_list': ChikenSoup.objects.all()
        }

    def tag_data(self):
        return {
            'tag_list': Tag.objects.all()
        }

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left = []

        right = []

        left_has_more = False

        right_has_more = False

        first = False

        last = False

        page_number = page.number

        total_pages = paginator.num_pages

        page_range = paginator.page_range

        if page_number == 1:

            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:

            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class BlogView(ListView):
    """
    博客视图
    """
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'post_list'
    paginate_by = 8

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)
        tag_data = self.tag_data()
        context.update(pagination_data)
        context.update(tag_data)
        return context

    def tag_data(self):
        return {
            'tag_list': Tag.objects.all()
        }

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left = []

        right = []

        left_has_more = False

        right_has_more = False

        first = False

        last = False

        page_number = page.number

        total_pages = paginator.num_pages

        page_range = paginator.page_range

        if page_number == 1:

            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:

            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class CategoryView(BlogView):
    """
    分类视图
    """

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/article.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        self.object.increase_views()

        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])

        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def tag_data(self):
        return {
            'tag_list': Tag.objects.all()
        }

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        tag_data = self.tag_data()
        context.update(tag_data)
        context.update({
            'form': form,
            'comment_list': comment_list
        })

        return context


class TagView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_data = self.tag_data()

        context.update(tag_data)
        return context

    def tag_data(self):
        return {
            'tag_list': Tag.objects.all()
        }

# class ImgView(ListView):
#     """
#     图库视图
#     """
#     model = Post
#     template_name = 'blog/img.html'
#     context_object_name = 'img_list'
#     paginate_by = 4
#
#     def get_context_data(self, **kwargs):
#
#         context = super().get_context_data(**kwargs)
#         paginator = context.get('paginator')
#         page = context.get('page_obj')
#         is_paginated = context.get('is_paginated')
#
#         pagination_data = self.pagination_data(paginator, page, is_paginated)
#         img_data = self.img_data()
#         context.update(img_data)
#         context.update(pagination_data)
#
#         print(context)
#         return context
#
#     def img_data(self):
#         return {
#             'img_list': Img.objects.all().order_by("-upload_time")
#         }
#
#
#     def pagination_data(self, paginator, page, is_paginated):
#         if not is_paginated:
#             return {}
#
#         left = []
#
#         right = []
#
#         left_has_more = False
#
#         right_has_more = False
#
#         first = False
#
#         last = False
#
#         page_number = page.number
#
#         total_pages = paginator.num_pages
#
#         page_range = paginator.page_range
#
#         if page_number == 1:
#
#             right = page_range[page_number:page_number + 2]
#
#             if right[-1] < total_pages - 1:
#                 right_has_more = True
#
#             if right[-1] < total_pages:
#                 last = True
#
#         elif page_number == total_pages:
#
#             left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
#
#             if left[0] > 2:
#                 left_has_more = True
#
#             if left[0] > 1:
#                 first = True
#         else:
#             left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
#             right = page_range[page_number:page_number + 2]
#
#             # 是否需要显示最后一页和最后一页前的省略号
#             if right[-1] < total_pages - 1:
#                 right_has_more = True
#             if right[-1] < total_pages:
#                 last = True
#
#             # 是否需要显示第 1 页和第 1 页后的省略号
#             if left[0] > 2:
#                 left_has_more = True
#             if left[0] > 1:
#                 first = True
#
#         data = {
#             'left': left,
#             'right': right,
#             'left_has_more': left_has_more,
#             'right_has_more': right_has_more,
#             'first': first,
#             'last': last,
#         }
#
#         return data


def homepage(request):
    """
    首页视图
    :param request:
    :return:
    """
    # 获取文章
    post_list = Post.objects.all().order_by('-created_time')

blogproject/templates/blog/blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}

{% block main %}

    <!-- content start -->
    <div class="am-g am-g-fixed blog-fixed">

        <!-- 文章目录 -->
        <div class="am-u-md-8 am-u-sm-12">

            {% for post in post_list %}
                <article class="am-g blog-entry-article">
                    <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                        <img src="{{ post.img.url }}" alt="" class="am-u-sm-12" width="400" height="165">
                    </div>
                    <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                        <span><a href="{{ post.category.get_absolute_url }}" class="blog-color">{{ post.category }} &nbsp;</a></span>
                        <span> @{{ post.author }} &nbsp;</span>
                        <span>{{ post.created_time }}</span>
                        <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                        <p>
                            {{ post.excerpt }}
                        </p>
                        <p><a href="" class="blog-continue">continue reading</a></p>
                    </div>
                </article>
            {% endfor %}
            {% if  is_paginated %}
                <ul class="am-pagination">
                {% if page_obj.has_previous %}
                    <li class="am-pagination-prev"><a href="?page={{ page_obj.previous_page_number }}">&laquo; Prev</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="am-pagination-next"><a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
                {% endif %}
            </ul>
            {% endif %}

        </div>

        <!-- 侧边栏 -->
        <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>About ME</span></h2>
                <img src="{% static 'blog/images/icon.jpeg' %}" alt="about me" class="blog-entry-img"
                     style="border-radius: 90%; width: 120px">
                <p>刘十一</p>
                <p>
                    爱生活、爱写字、爱摄影、爱代码。
                </p>
                <p>放荡不羁 崇尚自由 追求卓越</p>
            </div>
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>Contact ME</span></h2>
                <p>
                    <!--QQ 暂时不要-->
                    <a href="http://shang.qq.com/email/stop/email_stop.html?qq=1181107503&sig=a1c657365db7e82805ea4b2351081fc3ebcde159f8ae49b1&tttt=1"
                       target="_blank"><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>
                    <!-- 微信二维码悬浮显示 -->
                    <a class="social weixin" href="javascript:">
                        <img src="{% static 'blog/images/MyWechat.png' %}" alt="微信二维码">
                        <span class="am-icon-weixin am-icon-fw blog-icon"></span>
                    </a>
                    <a href="https://weibo.com/u/1932058985" target="view_window"><span
                            class="am-icon-weibo am-icon-fw blog-icon"></span></a>
                    <a href="https://github.com/LiuShiYi1027" target="view_window"><span
                            class="am-icon-github am-icon-fw blog-icon"></span></a>
                    <!-- 这个不知道是什么鬼东西 -->
                    <!--<a href=""><span class="am-icon-reddit am-icon-fw blog-icon"></span></a>-->
                </p>
            </div>
            <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
                    <h2 class="blog-title"><span>TAG cloud</span></h2>
                    <div class="am-u-sm-12 blog-clear-padding">
                        {% for tag in tag_list %}
                            <a href="{% url 'blog:tag' tag.pk %}" class="blog-tag">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            <!-- 将其隐藏 -->
            <!--<div class="blog-sidebar-widget blog-bor">-->
            <!--<h2 class="blog-title"><span>么么哒</span></h2>-->
            <!--<ul class="am-list">-->
            <!--<li><a href="#">每个人都有一个死角， 自己走不出来，别人也闯不进去。</a></li>-->
            <!--<li><a href="#">我把最深沉的秘密放在那里。</a></li>-->
            <!--<li><a href="#">你不懂我，我不怪你。</a></li>-->
            <!--<li><a href="#">每个人都有一道伤口， 或深或浅，盖上布，以为不存在。</a></li>-->
            <!--</ul>-->
            <!--</div>-->
        </div>
    </div>
    <!-- content end -->
    </div>
{% endblock main %}

blogproject/templates/blog/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="am-g am-g-fixed blog-fixed">

        <!-- banner start -->
        <div class="am-g am-g-fixed blog-fixed am-u-sm-centered blog-article-margin">
            <div data-am-widget="slider" class="am-slider am-slider-b1" data-am-slider='{&quot;controlNav&quot;:false}'>
                <ul class="am-slides">
                    {% for chicken_soup in chicken_soup_list %}
                        <li>
                            <img src="{{ chicken_soup.img.url }}" width="1434" height="503" >
                            <div class="blog-slider-desc am-slider-desc ">
                                <div class="blog-text-center blog-slider-con">
                                    <h1 class="blog-h-margin">总在思考一句积极的话</h1>
                                    <span class="blog-color">
                                    @ {{ chicken_soup.reference }}
                                </span>
                                    <p>
                                        {{ chicken_soup.content }}
                                    </p>

                                    <span class="blog-bor">
                                {{ chicken_soup.created_time }}
                            </span>
                                    <br><br><br><br><br><br><br>
                                </div>
                            </div>
                        </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
        <!-- banner end -->

        <!-- content start -->
        <div class="am-g am-g-fixed blog-fixed">

            <!-- 文章目录 -->
            <div class="am-u-md-8 am-u-sm-12">

                {% for post in post_list %}
                    <article class="am-g blog-entry-article">
                        <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                            <img src="{{ post.img.url }}" alt="" class="am-u-sm-12" width="400" height="165">
                        </div>
                        <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                            <span><a href="{{ post.category.get_absolute_url }}" class="blog-color">{{ post.category }} &nbsp;</a></span>
                            <span> @{{ post.author }} &nbsp;</span>
                            <span>{{ post.created_time }}</span>
                            <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                            <p>
                                {{ post.excerpt }}
                            </p>
                            <p><a href="" class="blog-continue">continue reading</a></p>
                        </div>
                    </article>
                {% endfor %}
                {% if  is_paginated %}
                    <ul class="am-pagination">
                        {% if page_obj.has_previous %}
                            <li class="am-pagination-prev"><a href="?page={{ page_obj.previous_page_number }}">&laquo;
                                Prev</a></li>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li class="am-pagination-next"><a href="?page={{ page_obj.next_page_number }}">Next
                                &raquo;</a></li>
                        {% endif %}
                    </ul>
                {% endif %}

            </div>

            <!-- 侧边栏 -->
            <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
                <div class="blog-sidebar-widget blog-bor">
                    <h2 class="blog-text-center blog-title"><span>About ME</span></h2>
                    <img src="{% static 'blog/images/icon.jpeg' %}" alt="about me" class="blog-entry-img"
                         style="border-radius: 90%; width: 120px">
                    <p>刘十一</p>
                    <p>
                        爱生活、爱写字、爱摄影、爱代码。
                    </p>
                    <p>放荡不羁 崇尚自由 追求卓越</p>
                </div>
                <div class="blog-sidebar-widget blog-bor">
                    <h2 class="blog-text-center blog-title"><span>Contact ME</span></h2>
                    <p>
                        <!--QQ 暂时不要-->
                        <a href="http://shang.qq.com/email/stop/email_stop.html?qq=1181107503&sig=a1c657365db7e82805ea4b2351081fc3ebcde159f8ae49b1&tttt=1"
                           target="_blank"><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>
                        <!-- 微信二维码悬浮显示 -->
                        <a class="social weixin" href="javascript:">
                            <img src="{% static 'blog/images/MyWechat.png' %}" alt="微信二维码">
                            <span class="am-icon-weixin am-icon-fw blog-icon"></span>
                        </a>
                        <a href="https://weibo.com/u/1932058985" target="view_window"><span
                                class="am-icon-weibo am-icon-fw blog-icon"></span></a>
                        <a href="https://github.com/LiuShiYi1027" target="view_window"><span
                                class="am-icon-github am-icon-fw blog-icon"></span></a>
                        <!-- 这个不知道是什么鬼东西 -->
                        <!--<a href=""><span class="am-icon-reddit am-icon-fw blog-icon"></span></a>-->
                    </p>
                </div>
                <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
                    <h2 class="blog-title"><span>TAG cloud</span></h2>
                    <div class="am-u-sm-12 blog-clear-padding">
                        {% for tag in tag_list %}
                            <a href="{% url 'blog:tag' tag.pk %}" class="blog-tag">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <!-- 将其隐藏 -->
                <!--<div class="blog-sidebar-widget blog-bor">-->
                <!--<h2 class="blog-title"><span>么么哒</span></h2>-->
                <!--<ul class="am-list">-->
                <!--<li><a href="#">每个人都有一个死角， 自己走不出来，别人也闯不进去。</a></li>-->
                <!--<li><a href="#">我把最深沉的秘密放在那里。</a></li>-->
                <!--<li><a href="#">你不懂我，我不怪你。</a></li>-->
                <!--<li><a href="#">每个人都有一道伤口， 或深或浅，盖上布，以为不存在。</a></li>-->
                <!--</ul>-->
                <!--</div>-->
            </div>
        </div>
        <!-- content end -->
    </div>
{% endblock main %}

blogproject/templates/blog/img.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
    <!-- content start -->
    <div class="am-g am-g-fixed blog-fixed">

        <!-- 图片库 -->
        <div class="am-u-md-8 am-u-sm-12">
            <figure data-am-widget="figure" class="am am-figure am-figure-default "
                    data-am-figure="{ pureview: 'true' }">
                <div class="am-g am-g-fixed" id="container">
                    <table>
                        {% for img in img_list %}
                            <tr>

                                <td style="width: 300px">
                                    <img style="width: 300px" src="{{ img.img.url }}" alt="">&nbsp;
                                </td>
                                <td style="width: 300px">
                                    <h1 align="center">&nbsp;&nbsp;{{ img.name }}&nbsp;&nbsp;</h1>
                                    <p align="center" class="blog-color">
                                        &nbsp;&nbsp;@ {{ img.author }} {{ img.upload_time|date:"Y-m-d" }}&nbsp;&nbsp;</p>
                                    <p align="center"> &nbsp;&nbsp; {{ img.params }} &nbsp;&nbsp; </p>
                                    <p align="center">&nbsp;&nbsp;{{ img.description }}&nbsp;&nbsp;</p>
                                </td>
                            </tr>
                        {% endfor %}

                    </table>

                </div>
            </figure>
        </div>

        <!-- 侧边栏 -->
        <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>About ME</span></h2>
                <img src="{% static 'blog/images/icon.jpeg' %}" alt="about me" class="blog-entry-img"
                     style="border-radius: 90%; width: 120px">
                <p>刘十一</p>
                <p>
                    爱生活、爱写字、爱摄影、爱代码。
                </p>
                <p>放荡不羁 崇尚自由 追求卓越</p>
            </div>
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>Contact ME</span></h2>
                <p>
                    <!--QQ 暂时不要-->
                    <a href="http://shang.qq.com/email/stop/email_stop.html?qq=1181107503&sig=a1c657365db7e82805ea4b2351081fc3ebcde159f8ae49b1&tttt=1"
                       target="_blank"><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>
                    <!-- 微信二维码悬浮显示 -->
                    <a class="social weixin" href="javascript:">
                        <img src="{% static 'blog/images/MyWechat.png' %}" alt="微信二维码">
                        <span class="am-icon-weixin am-icon-fw blog-icon"></span>
                    </a>
                    <a href="https://weibo.com/u/1932058985" target="view_window"><span
                            class="am-icon-weibo am-icon-fw blog-icon"></span></a>
                    <a href="https://github.com/LiuShiYi1027" target="view_window"><span
                            class="am-icon-github am-icon-fw blog-icon"></span></a>
                    <!-- 这个不知道是什么鬼东西 -->
                    <!--<a href=""><span class="am-icon-reddit am-icon-fw blog-icon"></span></a>-->
                </p>
            </div>
            <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
                <h2 class="blog-title"><span>TAG cloud</span></h2>
                <div class="am-u-sm-12 blog-clear-padding">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="blog-tag">{{ tag.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- content end -->
    </div>


{% endblock %}

blogproject/templates/blog/timeline.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}

    <!-- content srart -->
    <div class="am-g am-g-fixed blog-fixed blog-content">
        <div class="am-u-sm-12">
            <h1 class="blog-text-center">-- 存档 --</h1>
            <div class="timeline-year">

                    {% for post in post_list %}
                        <ul>
                        <li>
                            <span class="am-u-sm-4 am-u-md-2 timeline-span">{{ post.created_time|date:"Y-m-d" }}</span>
                            <span class="am-u-sm-8 am-u-md-6"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></span>
                            <span class="am-u-sm-4 am-u-md-2 am-hide-sm-only">{{ post.category }}</span>
                            <span class="am-u-sm-4 am-u-md-2 am-hide-sm-only">{{ post.author }}</span>
                        </li>
                        </ul>
                    {% endfor %}

            </div>
            <hr>
        </div>

    </div>
    <!-- content end -->

{% endblock %}